# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = [""]
cloned_from = "https://github.com/fastly/compute-starter-kit-typescript-default"
description = ""
language = "javascript"
manifest_version = 3
name = "fastly-htmlwriter"
service_id = "5aUsDlK6vnBLDyNDhVTMnM"

[local_server]

[scripts]
  build = "npm run build"
  post_init = "npm install"

[backends]
    name = "ulule"
    address = "fr.ulule.com"
    port = 443
    use_ssl = true