# This file describes a Fastly Compute package. To learn more visit:
# https://www.fastly.com/documentation/reference/compute/fastly-toml

authors = [""]
cloned_from = "https://github.com/fastly/compute-starter-kit-typescript-default"
description = ""
language = "javascript"
manifest_version = 3
name = "fastly-htmlwriter"
service_id = "5aUsDlK6vnBLDyNDhVTMnM"

[local_server]

[scripts]
  build = "npm run build"
  post_init = "npm install"

[local_server.backends.ulule]
    url = "https://fr.ulule.com"

[local_server.backends.pageworkers-demo]
    url = "https://pageworkers-demo.ftl.page"

[local_server.backends.pageworkers-local]
    url = "http://localhost:8080"